using System.IO;
using System.IO.Compression;
using System.Text;
using System.Globalization;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace ReeFont;
public static class ModExporter {
 public static string Clean(string s)=>string.Concat(s.Select(c=>char.IsControl(c)||c=='='?' ':c)).Trim();
 public static string FileName(Game game,string font,string[] languages) {
  var name=$"REEFont-{game.Id}-{Path.GetFileNameWithoutExtension(font)}-{string.Join('-',languages)}-1.0.zip";
  return string.Concat(name.Select(c=>Path.GetInvalidFileNameChars().Contains(c)?'_':c));
 }
 // Generated information card, deliberately not presented as an in-game screenshot.
 public static byte[] Preview(Game game,string font,string[] languages) {
  var visual=new DrawingVisual(); using(var d=visual.RenderOpen()) {
   d.DrawRectangle(new SolidColorBrush(Color.FromRgb(6,18,20)),null,new Rect(0,0,960,540));
   void Text(string s,double y,double size,Brush brush) { var text=new FormattedText(s,CultureInfo.InvariantCulture,FlowDirection.LeftToRight,new Typeface("Segoe UI"),size,brush,1){MaxTextWidth=864,MaxTextHeight=110,Trimming=TextTrimming.CharacterEllipsis}; d.DrawText(text,new Point(48,y)); }
   Text("REE FONT TOOL  /  FONT REPLACEMENT",40,23,Brushes.DarkTurquoise);
   Text(game.Name,110,34,Brushes.White); Text(Path.GetFileNameWithoutExtension(font),230,30,Brushes.DarkTurquoise);
   Text("Languages: "+string.Join(" / ",languages.Select(x=>x switch {"sc"=>"Simplified Chinese","tc"=>"Traditional Chinese",_=>"English"})),320,22,Brushes.White);
   Text("caicaiying  ·  bilibili.com/8480063",405,20,Brushes.Gray);
   Text("Mod information card — not an in-game screenshot",464,16,Brushes.Gray);
  }
  var bitmap=new RenderTargetBitmap(960,540,96,96,PixelFormats.Pbgra32); bitmap.Render(visual);
  var encoder=new JpegBitmapEncoder{QualityLevel=90}; encoder.Frames.Add(BitmapFrame.Create(bitmap)); using var stream=new MemoryStream(); encoder.Save(stream); return stream.ToArray();
 }
 public static void Export(Game game,string font,string[] languages,string destination,byte[] preview) {
  if(languages.Length==0) throw new IOException("Select a language / 请选择语言");
  var paths=languages.SelectMany(x=>game.Fonts.TryGetValue(x,out var p)?p:throw new IOException("Unsupported language / 不支持的语言")).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
  if(paths.Length==0) throw new IOException("No font targets / 没有目标字体");
  var data=Engine.Encode(Engine.ReadFont(font));
  if(!Path.GetExtension(destination).Equals(".zip",StringComparison.OrdinalIgnoreCase)) throw new IOException("Choose a .zip destination / 请使用 .zip 扩展名");
  if(Path.GetFullPath(destination).Equals(Path.GetFullPath(font),StringComparison.OrdinalIgnoreCase)) throw new IOException("Cannot overwrite source font");
  var title=$"{Clean(game.Name)} - {Clean(Path.GetFileNameWithoutExtension(font))} [{string.Join(", ",languages)}]";
  var ini=$"name={title}\r\nversion=1.0\r\ndescription=Replaces {string.Join(", ",languages)} font resources with {Clean(Path.GetFileNameWithoutExtension(font))}. Generated by REE Font Tool. Install for the matching game/version in Fluffy Mod Manager; loading requirements depend on the game.\r\nauthor=caicaiying\r\nhomepage=https://space.bilibili.com/8480063\r\nscreenshot=screenshot.jpg\r\n";
  string temp=destination+"."+Guid.NewGuid().ToString("N")+".tmp";
  try {
   using(var file=new FileStream(temp,FileMode.CreateNew,FileAccess.ReadWrite,FileShare.None)) {
    using(var zip=new ZipArchive(file,ZipArchiveMode.Create,true)) {
     void Add(string path,byte[] bytes) { using var target=zip.CreateEntry(path,CompressionLevel.Optimal).Open(); target.Write(bytes); }
     Add("modinfo.ini",new UTF8Encoding(false).GetBytes(ini)); Add("screenshot.jpg",preview);
     foreach(var p in paths) { Engine.Safe(Path.GetTempPath(),p); if(!p.StartsWith("natives/")||!p.EndsWith(".oft.1")) throw new IOException("Invalid mod target"); Add(p,data); }
    } file.Flush(true);
   }
   File.Move(temp,destination,true);
  } finally { if(File.Exists(temp)) File.Delete(temp); }
 }
}
